"""Initial schema with proper types

Revision ID: 556effb5af35
Revises:
Create Date: 2026-01-14 16:37:42.179276

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "556effb5af35"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drafts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("sender", sa.String(length=500), nullable=False),
        sa.Column("recipient", sa.String(length=500), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("time", sa.String(length=8), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), server_default="", nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drafts")),
    )
    op.create_index("ix_drafts_date_time", "drafts", ["date", "time"], unique=False)
    op.create_index(op.f("ix_drafts_sender"), "drafts", ["sender"], unique=False)
    op.create_index(op.f("ix_drafts_uid"), "drafts", ["uid"], unique=True)
    op.create_table(
        "inbox",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("sender", sa.String(length=500), nullable=False),
        sa.Column("recipient", sa.String(length=500), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("time", sa.String(length=8), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), server_default="", nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("flagged", sa.Boolean(), server_default="0", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox")),
    )
    op.create_index(
        "ix_inbox_date_time", "inbox", ["date", "time"], unique=False, sqlite_where=None
    )
    op.create_index(
        "ix_inbox_flagged",
        "inbox",
        ["flagged"],
        unique=False,
        sqlite_where=sa.text("flagged = 1"),
    )
    op.create_index(op.f("ix_inbox_sender"), "inbox", ["sender"], unique=False)
    op.create_index(op.f("ix_inbox_uid"), "inbox", ["uid"], unique=True)
    op.create_table(
        "sent",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("sender", sa.String(length=500), nullable=False),
        sa.Column("recipient", sa.String(length=500), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("time", sa.String(length=8), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), server_default="", nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="0", nullable=False),
        sa.Column(
            "sent_status",
            sa.String(length=20),
            server_default="pending",
            nullable=False,
        ),
        sa.Column("send_at", sa.String(length=26), nullable=True),
        sa.CheckConstraint(
            "sent_status IN ('pending', 'sent', 'failed')",
            name=op.f("ck_sent_ck_sent_status_values"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sent")),
    )
    op.create_index("ix_sent_date_time", "sent", ["date", "time"], unique=False)
    op.create_index(op.f("ix_sent_sender"), "sent", ["sender"], unique=False)
    op.create_index("ix_sent_status", "sent", ["sent_status"], unique=False)
    op.create_index(op.f("ix_sent_uid"), "sent", ["uid"], unique=True)
    op.create_table(
        "trash",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=1000), server_default="", nullable=False),
        sa.Column("sender", sa.String(length=500), nullable=False),
        sa.Column("recipient", sa.String(length=500), nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("time", sa.String(length=8), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("attachments", sa.Text(), server_default="", nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("flagged", sa.Boolean(), server_default="0", nullable=False),
        sa.Column("deleted_at", sa.String(length=26), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trash")),
    )
    op.create_index("ix_trash_date_time", "trash", ["date", "time"], unique=False)
    op.create_index("ix_trash_deleted_at", "trash", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_trash_sender"), "trash", ["sender"], unique=False)
    op.create_index(op.f("ix_trash_uid"), "trash", ["uid"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trash_uid"), table_name="trash")
    op.drop_index(op.f("ix_trash_sender"), table_name="trash")
    op.drop_index("ix_trash_deleted_at", table_name="trash")
    op.drop_index("ix_trash_date_time", table_name="trash")
    op.drop_table("trash")
    op.drop_index(op.f("ix_sent_uid"), table_name="sent")
    op.drop_index("ix_sent_status", table_name="sent")
    op.drop_index(op.f("ix_sent_sender"), table_name="sent")
    op.drop_index("ix_sent_date_time", table_name="sent")
    op.drop_table("sent")
    op.drop_index(op.f("ix_inbox_uid"), table_name="inbox")
    op.drop_index(op.f("ix_inbox_sender"), table_name="inbox")
    op.drop_index(
        "ix_inbox_flagged", table_name="inbox", sqlite_where=sa.text("flagged = 1")
    )
    op.drop_index("ix_inbox_date_time", table_name="inbox", sqlite_where=None)
    op.drop_table("inbox")
    op.drop_index(op.f("ix_drafts_uid"), table_name="drafts")
    op.drop_index(op.f("ix_drafts_sender"), table_name="drafts")
    op.drop_index("ix_drafts_date_time", table_name="drafts")
    op.drop_table("drafts")
    # ### end Alembic commands ###
